### ISSUE TITLE
Cyan color is hard to read due to low contrast

### ISSUE THREAD

**Issue by patrickhuijten** [JorritKeijzer/vscode-dayspring-theme#2]
The cyan color code used has too little contrast which makes it hard to read. Perhaps the contrast can be increased slightly?

![Screen Shot 2021-02-26 at 16 24 00](https://user-images.githubusercontent.com/36569812/109321420-6a895000-7851-11eb-824a-bf59ea9af862.png)

**Comment by JorritKeijzer** [comment]
Alright, fixed it
